from .file_loaders import NODE_CLASS_MAPPINGS as LOADER_CLASS_MAPPINGS
from .file_loaders import NODE_DISPLAY_NAME_MAPPINGS as LOADER_DISPLAY_NAME_MAPPINGS
from .file_savers import NODE_CLASS_MAPPINGS as SAVER_CLASS_MAPPINGS
from .file_savers import NODE_DISPLAY_NAME_MAPPINGS as SAVER_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOADER_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SAVER_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOADER_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SAVER_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
